services:
  mysql:
    container_name: mysql
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: task_managment_system
      MYSQL_ROOT_HOST: 'host.docker.internal'
      MYSQL_ROOT_PASSWORD: Tchepigo1!
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "3306:3306"
    volumes:
      - ./sql:/docker-entrypoint-initdb.d

  application:
    container_name: boozooka/task-managment-system
    build: .
    expose:
      - "8080"
    ports:
      - "8080:8080"
    environment:
      WAIT_HOSTS: mysql:3306
    depends_on:
      - mysql